### ISSUE TITLE
In your RDFS vocabulary, you are missing human readable names and descriptions of the classes and predicates

### ISSUE THREAD

**Issue by jakubklimek** [adrianPascan/WS#1]
In your RDFS vocabulary, you are missing human readable names and descriptions of the classes and predicates, i.e. using `rdfs:label` and `rdfs:comment` so that the data contains the definitions.

**Comment by AdrianPascan** [comment]
I added `rdfs:label` and `rdfs:comment` in my RDFS vocabulary
